language: java
script: ant test
jdk:
  - openjdk7
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-protobuf python-mako junit4
 - sudo ant install-generator
notifications:
  recipients:
    - ralf@embarkmobile.com

